baseURL = 'https://krlosaren.com/'
languageCode = 'es'
DefaultContentLanguage = 'es'
title = "Carlos López Zavarce"
copyright = "© 2026, Carlos López Zavarce"
enableInlineShortcodes = true
ignoreErrors = ["error-remote-getjson"]

theme = "paper"

[pagination]
  pagerSize = 6

[params]
  color = 'gray'
  github = 'krlosaren'
  linkedin = 'carloslopezzavarce'
  avatar = '/profile_img.jpeg'
  name = 'Carlos López Zavarce'
  bio = 'DevOps & Cloud Engineer | Solutions Architect'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = 'dracula'

[menu]
  [[menu.main]]
    identifier = "about"
    name = "Acerca"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "posts"
    name = "Blog"
    url = "/posts/"
    weight = 20
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 30

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[privacy]
  [privacy.youtube]
    disabled = false
    privacyEnhanced = true
